const ShapeGeneratorConst = {
  MIRRORED_SHIP: 'm',
  INVERTED_MIRRORED_SHIP: 'mv'
};

const ShaderConst = {
  VERTEX_SHADER: 'v',
  FRAGMENT_SHADER: 'f'
};

const AudioIndex = {
  WAVE_TYPE: 0,
  ATTACK_TIME: 1,
  SUSTAIN_TIME: 2,
  SUSTAIN_PUNCH: 3,
  DECAY_TIME: 4,
  START_FREQUENCY: 5,
  MIN_FREQUENCY: 6,
  SLIDE: 7,
  DELTA_SLIDE: 8,
  VIBRATO_DEPTH: 9,
  VIBRATO_SPEED: 10,
  CHANGE_AMOUNT: 11,
  CHANGE_SPEED: 12,
  SQUARE_DUTY: 13,
  DUTY_SWEEP: 14,
  REPEAT_SPEED: 15,
  PHASER_OFFSET: 16,
  PHASER_SWEEP: 17,
  LP_FILTER_CUTOFF: 18,
  LP_FILTER_CUTOFF_SWEEP: 19,
  LP_FILTER_RESONANCE: 20,
  HP_FILTER_CUTOFF: 21,
  HP_FILTER_CUTOFF_SWEEP: 22,
  MASTER_VOLUME: 23
};

const PathConst = {
  MIN_SHIPS: 2,
  MAX_SHIPS: 7
};

const GameConst = {
  WIDTH: 800,
  HEIGHT: 600,
  SHIP_WIDTH: 50,
  SHIP_HEIGHT: 50
};

const ObjectIndex = {
  SEED: 0,
  SEED_SHAPE_STR: 1,
  GENERATED_SHAPES: 2,
  DOM: 3,
  WIDTH: 4,
  HEIGHT: 5,
  POSITION_X: 6,
  POSITION_Y: 7,
  TICK: 8,
  DESTROYED: 9,
  OBJECT_TYPE: 10,
  PROJECTILE_COLLISION: 11
}

const ObjectTypeIndex = {
  PLAYER: 0,
  PLAYER_PROJECTILE: 1,
  ENEMY: 2,
  ENEMY_PROJECTILE: 3
}

const BoundingBoxIndex = {
  POSITION_X: 0,
  POSITION_Y: 1,
  WIDTH: 2,
  HEIGHT: 3
};

const ShapeIndex = {
    COLOR: 0,
    RADIUS: 1,
    POINTS: 2,
    BOUNDING_BOX: 3
};

const PathIndex = {
  SEGMENTS: 0,
  LAST_KNOWN_SEGMENT: 1
};

const PathSegmentIndex = {
  START_TIME: 0,
  END_TIME: 1,
  DURATION: 2,
  PERCENT_PER_MILLISECOND: 3,
  START_POINT: 4,
  END_POINT: 5,
  CONTROL_POINT: 6
};

const EnemyConfigIndex = {
  SEED: 0,
  SEED_SHAPE_STR: 1
};

const LevelSpecConst = {
  ON_ENTER: '0',
  ON_EXIT: '1'
};
