const AudioIndex = {
  WAVE_TYPE: 0,
  ATTACK_TIME: 1,
  SUSTAIN_TIME: 2,
  SUSTAIN_PUNCH: 3,
  DECAY_TIME: 4,
  START_FREQUENCY: 5,
  MIN_FREQUENCY: 6,
  SLIDE: 7,
  DELTA_SLIDE: 8,
  VIBRATO_DEPTH: 9,
  VIBRATO_SPEED: 10,
  CHANGE_AMOUNT: 11,
  CHANGE_SPEED: 12,
  SQUARE_DUTY: 13,
  DUTY_SWEEP: 14,
  REPEAT_SPEED: 15,
  PHASER_OFFSET: 16,
  PHASER_SWEEP: 17,
  LP_FILTER_CUTOFF: 18,
  LP_FILTER_CUTOFF_SWEEP: 19,
  LP_FILTER_RESONANCE: 20,
  HP_FILTER_CUTOFF: 21,
  HP_FILTER_CUTOFF_SWEEP: 22,
  MASTER_VOLUME: 23
};

const GameIndex = {
  WIDTH: 800,
  HEIGHT: 600
};

const ObjectIndex = {
  SEED: 0,
  SEED_SHAPE_STR: 1,
  GENERATED_SHAPES: 2,
  DOM: 3,
  WIDTH: 4,
  HEIGHT: 5,
  POSITION_X: 6,
  POSITION_Y: 7,
  TICK: 8,
  DESTROYED: 9,
  OBJECT_TYPE: 10,
  PROJECTILE_COLLISION: 11
}

const ObjectTypeIndex = {
  PLAYER: 0,
  PLAYER_PROJECTILE: 1,
  ENEMY: 2,
  ENEMY_PROJECTILE: 3
}

const BoundingBoxIndex = {
  POSITION_X: 0,
  POSITION_Y: 1,
  WIDTH: 2,
  HEIGHT: 3
};

const ShapeIndex = {
    COLOR: 0,
    RADIUS: 1,
    POINTS: 2,
    BOUNDING_BOX: 3
};
